const actions = {
    SEARCH_LOCATION: 'SEARCH_LOCATION',
    SET_ERROR: 'SET_ERROR',
    SELECT_LOCATION: 'SELECT_LOCATION',
    GET_FORECAST: 'GET_FORECAST',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES'
};
export {
    actions
};